copyright: Copyright &copy; 2020-2024 UNICEF
dev_addr: 127.0.0.1:8001
docs_dir: docs
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/unicef/hope-documentation
site_author: HOPE Team
site_description: ""
site_dir: ./~build/docs
site_name: HOPE
site_url: https://github.com/unicef/hct-mis
extra_css:
  - _theme/css/style.css
extra_javascript:
  - _theme/js/js.cookie.js
  - _theme/js/address.js
exclude_docs: |
  _includes/
  _docs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - mkdocs-click
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true
  - pymdownx.highlight:
      use_pygments: true
  - smarty
  - tables
  - toc:
      permalink: #
      baselevel: 1


extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

theme:
  name: "material"
  custom_dir: docs/_theme/overrides
  logo: _theme/img/logo.png
#  favicon: _theme/img/favicon.ico
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

plugins:
  - alias
  - gen-files:
      scripts:
        - docs/_scripts/build_glossary.py
  - autorefs
  - awesome-pages
#  - ezglossary
  - ezlinks
  - link-marker
  - mkdocstrings
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
      heading_offset: 0
#      start: <!--start-->
#      end: <!--end-->
      recursive: true
  - privacy
  - search
  - social
#  - autolinks
  - blog:
      blog_dir: howto
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: ""
      post_url_max_categories: 1
#      post_excerpt: optional
      post_readtime: false
      archive: false
      categories: false
      authors: false
      pagination: false
      draft: false
  - tags:
      tags_file: tags.md


hooks:
  - docs/_hooks/hooks.py
